# Theme
theme: jekyll-theme-hacker

# Margin
global:
  all: 1in
  bottom: 1.5in
print:
   left: 2in
   right: 2in
 screen:
   all: 0.5in
   top: 0.75in

# Analytics
analytics:
  provider: "google-gtag"
  google:
    measurement_id: "G-9DVN399R8T"
    anonymize_ip: # true, false (default)
